export const images = {
  genCapitaLogo : require('@/assets/icons/gencapitaLogo.svg'),
  iPhone : require('@/assets/icons/iPhone.svg'),
  buysell : require('@/assets/icons/buysell.svg'),
  portfolio : require('@/assets/icons/portfolio.svg'),
  trade : require('@/assets/icons/trade.svg'),
  money : require('@/assets/icons/money.svg'),
  security : require('@/assets/icons/security.svg'),
  listIcon : require('@/assets/icons/listIcon.svg'),
  paperMoney : require('@/assets/icons/paperMoney.svg'),
  CircleImage : require('@/assets/icons/circleImage.svg'),
  cardImage1 : require('@/assets/icons/graphCardImage.svg'),
  cardImage2 : require('@/assets/icons/community.svg'),
  cardImage3 : require('@/assets/icons/learning.svg'),
  womenLaughing : require('@/assets/icons/womenLaughing.svg'),
  downCaret : require('@/assets/icons/chevron-down (1).svg'),
  personal : require('@/assets/icons/personalAcct.gif.svg'),
  Corporate  : require('@/assets/icons/cooparate.svg'),
  Institutional : require('@/assets/icons/institutional.svg'),
  Enterprise : require('@/assets/icons/enterprise.svg'),
  overView : require('@/assets/icons/overView.svg'),
  phoneFrame : require('@/assets/icons/iPhone_12.svg'),
  NVDA : require('@/assets/icons/NVDA.svg'),
  flag : require('@/assets/icons/flag.svg'),
  close : require('@/assets/icons/x-close.svg'),
  infoCircle : require('@/assets/icons/info-circle 1.svg'),
  successfulWaitList  : require('@/assets/icons/succesful.svg'),
  faceBook :  require('@/assets/icons/Vector.svg'),
  whatsapp :  require('@/assets/icons/whatsapp-line 1.svg'),
  twitter :  require('@/assets/icons/twitter-x-fill 1.svg'),
  Insta :  require('@/assets/icons/instagram-line 1.svg'),
  linkedIn :  require('@/assets/icons/linkedin-fill 1.svg'),
  succssList :  require('@/assets/icons/succssList.svg'),
  microsoft :  require('@/assets/icons/microsoft.svg'),
  nvidia :  require('@/assets/icons/nvidia.svg'),
 
}; 